data_directory: "screenshots"

### 1代表灰度处理， 2代表二值化处理，如果需要使用二值化，需要将2放到前面, 0不使用
image_compress_level:
  - 0
  - 1
  - 2

### 0 表示普通识别，配合compress_level 1使用
### 1 标识精确识别，精确识别建议配合image_compress_level 2使用
api_version:
  - 0
  - 1

## 图像比例裁剪区域, (left, top, right, bottom)
crop_areas:
    '百万英雄':
      - 20
      - 140
      - 700
      - 650
    '冲顶大会':
      - 15
      - 165
      - 705
      - 595
    "芝士超人":
      - 37
      - 200
      - 683
      - 800
    "UC答题":
      - 0.186
      - 0.074
      - 0.683
      - 0.926

## 问题区域
question_areas:
    '百万英雄':
      - 20
      - 140
      - 700
      - 350
    '冲顶大会':
      - 15
      - 165
      - 705
      - 595
    "芝士超人":
      - 37
      - 200
      - 683
      - 295
    "UC答题":
      - 0.186
      - 0.074
      - 0.683
      - 0.926

## 答案选项区域
answer_areas:
    '百万英雄':
      - 20
      - 350
      - 700
      - 650
    '冲顶大会':
      - 15
      - 165
      - 705
      - 595
    "芝士超人":
      - 37
      - 295
      - 683
      - 600
    "UC答题":
      - 0.186
      - 0.074
      - 0.683
      - 0.926

## 图像上的白点位置（X,Y），该点判断为白色时，即认为弹出了题目框
white_points:
    '百万英雄':
      - 285
      - 115
    '冲顶大会':
      - 15
      - 165
    "芝士超人":
      - 290
      - 115
    "UC答题":
      - 0.186
      - 0.074

## 判断白点的阈值
white_threshold:
  - 230
  - 230
  - 230
## 判断白点的邻域大小
white_size:
  - 3
  - 3

# 截图预处理旋转方式，可选：no | left | right
rotate: "right"

# 从题目框出现到题目完全出现的时间
question_waits:
  '百万英雄': 1
  '冲顶大会': 1
  '芝士超人': 1
  'UC答题': 1

answer_time_limits:
  '百万英雄': 10
  '冲顶大会': 10
  '芝士超人': 10
  'UC答题': 10

detecting_interval: 0.1

### baidu orc
app_id: "yours"
app_key: "yours"
app_secret: "yours"

# ### baidu orc
# app_id: "10712738"
# app_key: "98QhwoCzoZxKoZbX5XWNPld4"
# app_secret: "MGYLv1BeHjWOGFc9IjZPfzuhlPlaBEWA "

### ocr.space
api_key: "6c851da45688957"

### 默认使用百度，每天封顶500次
### 如果你想要使用ocr.space的话，将ocrspace移动到前面,每个api_key每月支持25000次调用
prefer:
  - baidu
  - ocrspace

### enable chrome
enable_chrome: false

### 是否使用夜神模拟器
use_monitor: false
