data_directory: "screenshots"

### 1代表灰度处理， 2代表二值化处理，如果需要使用二值化，需要将2放到前面, 0不使用
image_compress_level:
  - 1
  - 0
  - 2

### 0 表示普通识别，配合compress_level 1使用
### 1 标识精确识别，精确识别建议配合image_compress_level 2使用
api_version:
  - 0
  - 1

## 图像比例裁剪区域, (left, top, right, bottom)
## 最终裁剪区域可表示为 (image_width * left, image_height * top, image_width * right, image_height * bottom)
crop_areas:
    '百万英雄':
      - 0.028
      - 0.11
      - 0.509
      - 0.972
    '冲顶大会':
      - 0.144
      - 0.020
      - 0.448
      - 0.965
    "芝士超人":
      - 0.156
      - 0.0509
      - 0.625
      - 0.949

answer_time_limits:
  '百万英雄': 1
  '冲顶大会': 10
  '芝士超人': 10

detecting_interval: 0.1

### baidu orc
app_id: "10708327"
app_key: "Ldu7vP3yaNb3Bpt8ny1Kck5i"
app_secret: "THBBvAsVBYEa03Xz5cX2PsGEpKHth2je"

### ocr.space
api_key: "6c851da45688957"

### 默认使用百度，每天封顶500次
### 如果你想要使用ocr.space的话，将ocrspace移动到前面,每个api_key每月支持25000次调用
prefer:
  - baidu
  - ocrspace

### enable chrome
enable_chrome: true

### 是否使用夜神模拟器
use_monitor: false